services:
  server:
    image: haaragard/evrima-server:latest
    restart: unless-stopped
    volumes:
      - server-data:/app
      - ./configs/Game.ini:/app/TheIsle/Saved/Config/LinuxServer/Game.ini:rw
      - ./configs/Engine.ini:/app/TheIsle/Saved/Config/LinuxServer/Engine.ini:rw
    ports:
      - "7777:7777/udp"
      - "10000:10000/tcp"
      - "27015:27015/udp"
volumes:
  server-data:
