;METADATA=(Diff=true, UseCommands=true)
[/Script/TheIsle.TIGameSession]
ServerName=Haaragards Isle
MapName=Gateway
MaxPlayerCount=100
bEnableHumans=false
bQueueEnabled=false
QueuePort=10000
bServerPassword=false
ServerPassword=password
bRconEnabled=true
RconPassword=rconpassword
RconPort=8888
bServerDynamicWeather=true
ServerDayLengthMinutes=45
ServerNightLengthMinutes=20
bServerWhitelist=false
bEnableGlobalChat=false
bSpawnPlants=true
bSpawnAI=true
AISpawnInterval=40
bEnableMigration=true
MaxMigrationTime=5400
GrowthMultiplier=10
bEnableMutations=true

[/Script/TheIsle.TIGameStateBase]
AdminsSteamIDs=76561198100669833
WhitelistIDs=
AllowedClasses=Hypsilophodon
AllowedClasses=Pachycephalosaurus
AllowedClasses=Stegosaurus
AllowedClasses=Tenontosaurus
AllowedClasses=Carnotaurus
AllowedClasses=Ceratosaurus
AllowedClasses=Deinosuchus
AllowedClasses=Diabloceratops
AllowedClasses=Omniraptor
AllowedClasses=Pteranodon
AllowedClasses=Troodon
AllowedClasses=Beipiaosaurus
AllowedClasses=Gallimimus
AllowedClasses=Dilophosaurus
AllowedClasses=Dryosaurus
AllowedClasses=Herrerasaurus

